<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>MDSplus - shots</title>
    <link rel="stylesheet" href="web/js/kalenda/kalendae.css" type="text/css" charset="utf-8">
    <script src="web/js/kalenda/kalendae.standalone.js" type="text/javascript" charset="utf-8"></script>
<style>
.info {
    background-color: red;
    border: none;
    cursor: pointer;
    width:  100%;
    height: 100%;
    color: transparent;
}
.cell {
    border: 1px solid black;
    height: 100%;
}
.cell0 {
    background-color: {{statusDefinitions[0][1]}};
}
.cell1 {
    background-color: {{statusDefinitions[1][1]}};
}
.cell2 {
    background-color: {{statusDefinitions[2][1]}};
    align=center;
}
.cell3 {
    background-color: {{statusDefinitions[3][1]}};
}
.cell4 {
    background-color: {{statusDefinitions[4][1]}};
}
.cell5 {
    background-color: {{statusDefinitions[5][1]}};
}
</style>

</head>

  <body style="font-family:Arial,Helvetica,sans-serif;">

{#
 # Block to show errors if present
 #}
{% if errorStr|length > 0 %}
  <div style="border-style: solid; border-width: 5px; border-color: red; margin:20px; padding:20px">
  {{ errorStr|nl2br }}
  </div>
{% endif %}


{#
 # Block to show messages if present (the shots' checked message)
 #}
{% if messageStr|length > 0 %}
  <div style="border-style: solid; border-width: 5px; border-color: lightgreen; margin:20px; padding:20px">
  <h3>{{ messageStr }}</h3>
  {% if messageSubStr|length > 0 %}
    {{ messageSubStr }}
  {% endif %}
  </div>
{% endif %}


{#
 # Date selection
 #}
<div style="display: inline-block; vertical-align: top; ">
<form id="date" name="homeBody" action="index.php" method="POST">
<input type="date" name="date" value="{{date}}" style="font-size:16pt;font-weight:bold;"/>
  <button name="subject" type="submit" value="setDate" style="font-size:16px;font-weight:bold;">
    Set Date
  </button>
  refresh after <input type="number" name="refresh" value="{{refresh}}" align="right" style="direction: rtl;width: 80px;"/>s (0 for never)
</div>

<hr>


{#
 # some logging information
 #}
Request from IP: <strong>{{ remoteIpAddress}}</strong> - Shots <strong>{{ shotDate }}...</strong>


{#
 # main status table
 #}
<table style="border: 1px solid black; border-collapse: collapse;" height="100%" width="100%">
  <tr>
    <td class="cell"></td>
    {% for x in listOfShots %}
      <td class="cell" align="center"> {{ x|slice(6) }} </td>
    {% endfor %}
  </tr>

  {% for x in listOfExpts %}
  <tr height="100%">
    <td class="cell">{{ x }}</td>
    {% for y in listOfShots %}
      {% set sts = tableOfStatus[loop.parent.loop.index0][loop.index0] %}
      <td class="cell cell{{sts}}">
      {% if sts == 2 %}
        {% if isAllowed[2] %}
          <input type='checkbox' name='check{{loop.parent.loop.index0}}x{{loop.index0}}' value='0'>
        {% endif %}
      {% elseif sts == 4 %}
        <form action="index.php" method="POST">
          <input type="hidden" name="info" value="{{ x }} {{ y }}"/>
          <input type="hidden" name="date" value="{{date}}"/>
          <input class="info" name="subject" type="submit" value="i"/>
        </form>
      {% endif %}
      </td>
    {% endfor %}
  </tr>
  {% endfor %}

</table>

{#
 # button to check shots
 #}
<h3>
  {% if isAllowed[2] %}
  <button name="subject" type="submit" value="copySelectedShots" style="font-size: 24px;">
    Copy selected shots
  </button>
  {% endif %}
</h3>

<hr>

</form>

{#
 # Description of color meaning
 #}
<div style="display: inline-block; vertical-align: top; ">
Legend <br>
<table>
  <tr>
  {% for x in statusDefinitions %}
    <td style="border: 1px solid black; background-color: {{x[1]}}; width: 200px">
    <strong>{{x[3]}}</strong><br>{{x[4]}}</td>
  {% endfor %}
  </tr>
</table>
</div>
<script type="text/javascript">
  if ({{refresh}}>0) {
    setTimeout(function () {
      document.getElementById("date").submit();
    },{{refresh}}*1000);
  }
</script>
  </body>
</html>

