<!DOCTYPE html>
<html>

  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>IPP shots</title>
    <link rel="stylesheet" href="web/js/kalenda/kalendae.css" type="text/css" charset="utf-8">
    <script src="web/js/kalenda/kalendae.standalone.js" type="text/javascript" charset="utf-8"></script>
  </head>

  <body>

    <h2> 
      <div style="vertical-align: middle;">
      <div style="display: inline-block; vertical-align: middle; margin: 0px 20px 0px 20px;">
        <a href="index.php"><img src="web/img/IPP-2000x2000_200dpi.jpg" alt="logo" height="84"></a>
      </div>

      <div style="display: inline-block; vertical-align: middle;">
	<a href="index.php">{{ title }}</a> </h2>
      </div>
      </div>
    <hr>
      
    {% block content %}{% endblock %}

    <hr>
  </body>
</html>
